# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-06-22 16:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('almacen', '0002_auto_20180622_0833'),
    ]

    operations = [
        migrations.AlterField(
            model_name='almacen',
            name='descripcion',
            field=models.CharField(max_length=200),
        ),
    ]
