# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-06-22 16:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('almacen', '0003_auto_20180622_1112'),
    ]

    operations = [
        migrations.AlterField(
            model_name='almacen',
            name='descripcion',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='almacen',
            name='proveedor',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='almacen',
            name='ubicacion',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='almacen',
            name='unidad',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
