# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-06-22 18:06
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('almacen', '0004_auto_20180622_1113'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='almacen',
            name='imagen',
        ),
    ]
