# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-06-22 20:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('almacen', '0005_remove_almacen_imagen'),
    ]

    operations = [
        migrations.AddField(
            model_name='almacen',
            name='costo',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='almacen',
            name='cantidad_caja',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='almacen',
            name='cantidad_rb',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='almacen',
            name='existencia',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
