# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2018-06-28 17:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('almacen', '0008_log'),
    ]

    operations = [
        migrations.AlterField(
            model_name='almacen',
            name='existencia',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
